{{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" "tekton-triggers-clusterrole") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-triggers-clusterrole
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources:
      - clustertriggerbindings
      - clusterinterceptors
    verbs: ["get", "list", "watch"]
{{- end }}