{{- if not (lookup "rbac.authorization.k8s.io/v1" "Role" .Values.namespace "tekton-triggers-role") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-triggers-role
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources:
      - eventlisteners
      - triggerbindings
      - triggertemplates
      - triggers
      - interceptors
      - eventlisteners/status
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
{{- end }}