apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
secrets:
  - name: redhat-auth
  - name: docker-auth
imagePullSecrets:
  - name: redhat-auth
  - name: docker-auth
  - name: reg-creds