namespace: connectivity-test
replicaCount: 3

git:
  gitUrl: https://github.com/devopsluka/connectivity-test-server-app
  gitBranch: main

serviceAccount:
  name: tekton-triggers-sa

image:
  repository: docker.io/devopsluka/connectivity-test-server
  tag: 1.0.0

service:
  port: 8080
  type: ClusterIP

resources:
  requests:
    cpu: '10m'
    memory: '100Mi'
  limits:
    cpu: '100m'
    memory: '1Gi'