apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: test-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: test-{{ .Release.Name }}
    spec:
      containers:
        - name: test-{{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
