apiVersion: v1
kind: Service
metadata:
  name: test-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: test-{{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: test-{{ .Release.Name }}
