apiVersion: v1
kind: Secret
metadata:
  name: docker-auth
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJkZXZvcHNsdWthIiwicGFzc3dvcmQiOiJkY2tyX3BhdF9ST2JYSWxhVTNRR2RyeUYzMnFkUkpUMWhrbzgiLCJhdXRoIjoiWkdWMmIzQnpiSFZyWVRwa1kydHlYM0JoZEY5U1QySllTV3hoVlROUlIyUnllVVl6TW5Ga1VrcFVNV2hyYnpnPSIsImVtYWlsIjoiIn19fQ==
type: kubernetes.io/dockerconfigjson
